# Generated by Django 4.2.7 on 2024-01-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('IMAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IMAGE_NAME', models.CharField(max_length=255)),
                ('IMAGE_TYPE', models.IntegerField(choices=[(1, '個人写真'), (2, 'アルバム写真'), (3, '動画')])),
                ('EVENT_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('ALBUM_ID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
