# Generated by Django 4.2.7 on 2024-01-31 02:03

import app_album.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('IMAGE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('IMAGE_NAME', models.CharField(max_length=255)),
                ('FILE_TYPE', models.IntegerField(choices=[(1, '個人写真'), (2, 'アルバム写真'), (3, '動画')])),
                ('EVENT_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('FILE', models.FileField(null=True, storage=app_album.models.S3MediaStorage(), upload_to=app_album.models.Photo.upload_path)),
                ('ALBUM_ID', models.IntegerField(blank=True, null=True)),
                ('CLASS_NAME', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='S3Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FILE_TYPE', models.IntegerField(choices=[(1, '個人写真'), (2, 'アルバム写真'), (3, '動画')])),
                ('FILE', models.FileField(null=True, storage=app_album.models.S3MediaStorage(), upload_to='')),
            ],
        ),
    ]
