# Generated by Django 4.2.7 on 2024-01-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
